### ISSUE TITLE
اشکال در اندازه

### ISSUE THREAD

**Issue by devbrisk** [alikhajavi74/ir_datetime_picker#3]
سلام
مشکلی تو پکیج شما وجود داره اینکه تو تبلت یا نسخه وب که عرض صفحه زیاده ویجت کشیده میشه و خیلی بزرگ میشه. به نظر میاد شما با استفاده از width کل صفحه، ویجت و تعیین سایز می کنین که برای مواقعی که عرض صفحه زیاد باشه مشکل ایجاد میشه.

**Comment by alikhajavi74** [comment]
سلام رفع شد
