### ISSUE TITLE
Background Color

### ISSUE THREAD

**Issue by RYLATECH** [alikhajavi74/ir_datetime_picker#4]
Hello, How can i change background color?

**Comment by alikhajavi74** [comment]
Hi you can use IRJalaliDatePicker widget for create your own DatePicker with any design. Check example to use
https://github.com/alikhajavi74/ir_datetime_picker/blob/master/example/lib/main.dart

**Comment by RYLATECH** [comment]
Thanks! Just this library doesn't have note or subtitle text?
If you added this widget to library it will be grate!

**Comment by alikhajavi74** [comment]
Again, you can use IRJalaliDatePicker widget for your own design with anything that you want!
